/* tslint:disable */
/* eslint-disable */
/**
 * Memory Cache Hub
 * A backend server for Memory Cache.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListProjectsResponse
 */
export interface ListProjectsResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof ListProjectsResponse
     */
    projects: Array<string>;
}

/**
 * Check if a given object implements the ListProjectsResponse interface.
 */
export function instanceOfListProjectsResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "projects" in value;

    return isInstance;
}

export function ListProjectsResponseFromJSON(json: any): ListProjectsResponse {
    return ListProjectsResponseFromJSONTyped(json, false);
}

export function ListProjectsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListProjectsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'projects': json['projects'],
    };
}

export function ListProjectsResponseToJSON(value?: ListProjectsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'projects': value.projects,
    };
}

