/* tslint:disable */
/* eslint-disable */
/**
 * Memory Cache Hub
 * A backend server for Memory Cache.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  SummarizeFileRequest,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    SummarizeFileRequestFromJSON,
    SummarizeFileRequestToJSON,
} from '../models/index';

export interface SummarizeFileApiV1SummarizeFilePostRequest {
    summarizeFileRequest: SummarizeFileRequest;
}

/**
 * 
 */
export class SummariesApi extends runtime.BaseAPI {

    /**
     * Summarize File
     */
    async summarizeFileApiV1SummarizeFilePostRaw(requestParameters: SummarizeFileApiV1SummarizeFilePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters.summarizeFileRequest === null || requestParameters.summarizeFileRequest === undefined) {
            throw new runtime.RequiredError('summarizeFileRequest','Required parameter requestParameters.summarizeFileRequest was null or undefined when calling summarizeFileApiV1SummarizeFilePost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/summarize_file`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SummarizeFileRequestToJSON(requestParameters.summarizeFileRequest),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Summarize File
     */
    async summarizeFileApiV1SummarizeFilePost(requestParameters: SummarizeFileApiV1SummarizeFilePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.summarizeFileApiV1SummarizeFilePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
