/* tslint:disable */
/* eslint-disable */
/**
 * Memory Cache Hub
 * A backend server for Memory Cache.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DeleteFileRequest,
  HTTPValidationError,
} from '../models/index';
import {
    DeleteFileRequestFromJSON,
    DeleteFileRequestToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface DeleteFileApiV1DeleteFileDeleteRequest {
    deleteFileRequest: DeleteFileRequest;
}

export interface ListFilesApiV1ListFilesProjectNameGetRequest {
    projectName: string;
}

export interface UploadFileApiV1UploadFilePostRequest {
    projectName: string;
    filePath: string;
    file: Blob;
}

/**
 * 
 */
export class FilesApi extends runtime.BaseAPI {

    /**
     * Delete File
     */
    async deleteFileApiV1DeleteFileDeleteRaw(requestParameters: DeleteFileApiV1DeleteFileDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters.deleteFileRequest === null || requestParameters.deleteFileRequest === undefined) {
            throw new runtime.RequiredError('deleteFileRequest','Required parameter requestParameters.deleteFileRequest was null or undefined when calling deleteFileApiV1DeleteFileDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/delete_file`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: DeleteFileRequestToJSON(requestParameters.deleteFileRequest),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete File
     */
    async deleteFileApiV1DeleteFileDelete(requestParameters: DeleteFileApiV1DeleteFileDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deleteFileApiV1DeleteFileDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Files
     */
    async listFilesApiV1ListFilesProjectNameGetRaw(requestParameters: ListFilesApiV1ListFilesProjectNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        if (requestParameters.projectName === null || requestParameters.projectName === undefined) {
            throw new runtime.RequiredError('projectName','Required parameter requestParameters.projectName was null or undefined when calling listFilesApiV1ListFilesProjectNameGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/list_files/{project_name}`.replace(`{${"project_name"}}`, encodeURIComponent(String(requestParameters.projectName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * List Files
     */
    async listFilesApiV1ListFilesProjectNameGet(requestParameters: ListFilesApiV1ListFilesProjectNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.listFilesApiV1ListFilesProjectNameGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Upload File
     */
    async uploadFileApiV1UploadFilePostRaw(requestParameters: UploadFileApiV1UploadFilePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters.projectName === null || requestParameters.projectName === undefined) {
            throw new runtime.RequiredError('projectName','Required parameter requestParameters.projectName was null or undefined when calling uploadFileApiV1UploadFilePost.');
        }

        if (requestParameters.filePath === null || requestParameters.filePath === undefined) {
            throw new runtime.RequiredError('filePath','Required parameter requestParameters.filePath was null or undefined when calling uploadFileApiV1UploadFilePost.');
        }

        if (requestParameters.file === null || requestParameters.file === undefined) {
            throw new runtime.RequiredError('file','Required parameter requestParameters.file was null or undefined when calling uploadFileApiV1UploadFilePost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters.projectName !== undefined) {
            formParams.append('project_name', requestParameters.projectName as any);
        }

        if (requestParameters.filePath !== undefined) {
            formParams.append('file_path', requestParameters.filePath as any);
        }

        if (requestParameters.file !== undefined) {
            formParams.append('file', requestParameters.file as any);
        }

        const response = await this.request({
            path: `/api/v1/upload_file`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Upload File
     */
    async uploadFileApiV1UploadFilePost(requestParameters: UploadFileApiV1UploadFilePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.uploadFileApiV1UploadFilePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
