/* tslint:disable */
/* eslint-disable */
/**
 * Memory Cache Hub
 * A backend server for Memory Cache.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddDirectoryToProjectRequest
 */
export interface AddDirectoryToProjectRequest {
    /**
     * 
     * @type {string}
     * @memberof AddDirectoryToProjectRequest
     */
    directory: string;
    /**
     * 
     * @type {string}
     * @memberof AddDirectoryToProjectRequest
     */
    projectName: string;
}

/**
 * Check if a given object implements the AddDirectoryToProjectRequest interface.
 */
export function instanceOfAddDirectoryToProjectRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "directory" in value;
    isInstance = isInstance && "projectName" in value;

    return isInstance;
}

export function AddDirectoryToProjectRequestFromJSON(json: any): AddDirectoryToProjectRequest {
    return AddDirectoryToProjectRequestFromJSONTyped(json, false);
}

export function AddDirectoryToProjectRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddDirectoryToProjectRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'directory': json['directory'],
        'projectName': json['project_name'],
    };
}

export function AddDirectoryToProjectRequestToJSON(value?: AddDirectoryToProjectRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'directory': value.directory,
        'project_name': value.projectName,
    };
}

