/* tslint:disable */
/* eslint-disable */
/**
 * Memory Cache Hub
 * A backend server for Memory Cache.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckLlamafileStatusRequest
 */
export interface CheckLlamafileStatusRequest {
    /**
     * 
     * @type {string}
     * @memberof CheckLlamafileStatusRequest
     */
    llamafileFilename: string;
}

/**
 * Check if a given object implements the CheckLlamafileStatusRequest interface.
 */
export function instanceOfCheckLlamafileStatusRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "llamafileFilename" in value;

    return isInstance;
}

export function CheckLlamafileStatusRequestFromJSON(json: any): CheckLlamafileStatusRequest {
    return CheckLlamafileStatusRequestFromJSONTyped(json, false);
}

export function CheckLlamafileStatusRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckLlamafileStatusRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'llamafileFilename': json['llamafile_filename'],
    };
}

export function CheckLlamafileStatusRequestToJSON(value?: CheckLlamafileStatusRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'llamafile_filename': value.llamafileFilename,
    };
}

