/* tslint:disable */
/* eslint-disable */
/**
 * Memory Cache Hub
 * A backend server for Memory Cache.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DownloadLlamafileByNameRequest
 */
export interface DownloadLlamafileByNameRequest {
    /**
     * 
     * @type {string}
     * @memberof DownloadLlamafileByNameRequest
     */
    llamafileFilename: string;
}

/**
 * Check if a given object implements the DownloadLlamafileByNameRequest interface.
 */
export function instanceOfDownloadLlamafileByNameRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "llamafileFilename" in value;

    return isInstance;
}

export function DownloadLlamafileByNameRequestFromJSON(json: any): DownloadLlamafileByNameRequest {
    return DownloadLlamafileByNameRequestFromJSONTyped(json, false);
}

export function DownloadLlamafileByNameRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DownloadLlamafileByNameRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'llamafileFilename': json['llamafile_filename'],
    };
}

export function DownloadLlamafileByNameRequestToJSON(value?: DownloadLlamafileByNameRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'llamafile_filename': value.llamafileFilename,
    };
}

