/* tslint:disable */
/* eslint-disable */
/**
 * Memory Cache Hub
 * A backend server for Memory Cache.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SummarizeFileRequest
 */
export interface SummarizeFileRequest {
    /**
     * 
     * @type {number}
     * @memberof SummarizeFileRequest
     */
    projectId: number;
    /**
     * 
     * @type {string}
     * @memberof SummarizeFileRequest
     */
    filePath: string;
}

/**
 * Check if a given object implements the SummarizeFileRequest interface.
 */
export function instanceOfSummarizeFileRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "projectId" in value;
    isInstance = isInstance && "filePath" in value;

    return isInstance;
}

export function SummarizeFileRequestFromJSON(json: any): SummarizeFileRequest {
    return SummarizeFileRequestFromJSONTyped(json, false);
}

export function SummarizeFileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SummarizeFileRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'projectId': json['project_id'],
        'filePath': json['file_path'],
    };
}

export function SummarizeFileRequestToJSON(value?: SummarizeFileRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'project_id': value.projectId,
        'file_path': value.filePath,
    };
}

